route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email-me'
receivers:
- name: 'email-me'
  email_configs:
  - to: 'uremail'
    from: 'uremail'
    smarthost: smtp.gmail.com:587
    auth_username: 'uremail'
    auth_identity: 'uremail'
    auth_password: 'app-password'